/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectRouteImport } from './routes/select'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as InternalDomainCheckRouteImport } from './routes/internal/domain-check'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as CliLoginRouteImport } from './routes/cli.login'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as _authenticatedOnboardingRouteImport } from './routes/__authenticated/onboarding'
import { Route as _authenticatedOrgSlugRouteImport } from './routes/__authenticated/$orgSlug'
import { Route as _authenticatedOrgSlugIndexRouteImport } from './routes/__authenticated/$orgSlug/index'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiTunnelRegisterRouteImport } from './routes/api/tunnel/register'
import { Route as ApiTunnelCheckSubdomainRouteImport } from './routes/api/tunnel/check-subdomain'
import { Route as ApiTunnelAuthRouteImport } from './routes/api/tunnel/auth'
import { Route as ApiSubscriptionsOrganizationIdRouteImport } from './routes/api/subscriptions/$organizationId'
import { Route as ApiOrganizationsCheckSlugRouteImport } from './routes/api/organizations/check-slug'
import { Route as ApiMeOrgsRouteImport } from './routes/api/me/orgs'
import { Route as ApiDomainVerifyOwnershipRouteImport } from './routes/api/domain/verify-ownership'
import { Route as ApiCliLoginRouteImport } from './routes/api/cli/login'
import { Route as ApiCliExchangeRouteImport } from './routes/api/cli/exchange'
import { Route as ApiCliCompleteRouteImport } from './routes/api/cli/complete'
import { Route as ApiCheckoutPolarRouteImport } from './routes/api/checkout/polar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiOrgSlugSubscriptionsRouteImport } from './routes/api/$orgSlug/subscriptions'
import { Route as ApiOrgSlugRequestsRouteImport } from './routes/api/$orgSlug/requests'
import { Route as ApiOrgSlugAuthTokensRouteImport } from './routes/api/$orgSlug/auth-tokens'
import { Route as _authenticatedOrgSlugTokensRouteImport } from './routes/__authenticated/$orgSlug/tokens'
import { Route as _authenticatedOrgSlugSubdomainsRouteImport } from './routes/__authenticated/$orgSlug/subdomains'
import { Route as _authenticatedOrgSlugSettingsRouteImport } from './routes/__authenticated/$orgSlug/settings'
import { Route as _authenticatedOrgSlugRequestsRouteImport } from './routes/__authenticated/$orgSlug/requests'
import { Route as _authenticatedOrgSlugMembersRouteImport } from './routes/__authenticated/$orgSlug/members'
import { Route as _authenticatedOrgSlugInstallRouteImport } from './routes/__authenticated/$orgSlug/install'
import { Route as _authenticatedOrgSlugDomainsRouteImport } from './routes/__authenticated/$orgSlug/domains'
import { Route as _authenticatedOrgSlugBillingRouteImport } from './routes/__authenticated/$orgSlug/billing'
import { Route as ApiOrgSlugTunnelsIndexRouteImport } from './routes/api/$orgSlug/tunnels/index'
import { Route as ApiOrgSlugSubdomainsIndexRouteImport } from './routes/api/$orgSlug/subdomains/index'
import { Route as ApiOrgSlugDomainsIndexRouteImport } from './routes/api/$orgSlug/domains/index'
import { Route as _authenticatedOrgSlugTunnelsIndexRouteImport } from './routes/__authenticated/$orgSlug/tunnels/index'
import { Route as _authenticatedOrgSlugSettingsIndexRouteImport } from './routes/__authenticated/$orgSlug/settings/index'
import { Route as ApiCliLoginStatusRouteImport } from './routes/api/cli/login/status'
import { Route as ApiOrgSlugTunnelsTunnelIdRouteImport } from './routes/api/$orgSlug/tunnels/$tunnelId'
import { Route as ApiOrgSlugSubdomainsSubdomainIdRouteImport } from './routes/api/$orgSlug/subdomains/$subdomainId'
import { Route as ApiOrgSlugStatsTunnelRouteImport } from './routes/api/$orgSlug/stats/tunnel'
import { Route as ApiOrgSlugStatsProtocolRouteImport } from './routes/api/$orgSlug/stats/protocol'
import { Route as ApiOrgSlugStatsOverviewRouteImport } from './routes/api/$orgSlug/stats/overview'
import { Route as ApiOrgSlugStatsBandwidthRouteImport } from './routes/api/$orgSlug/stats/bandwidth'
import { Route as ApiOrgSlugPortalPolarRouteImport } from './routes/api/$orgSlug/portal/polar'
import { Route as ApiOrgSlugDomainsDomainIdRouteImport } from './routes/api/$orgSlug/domains/$domainId'
import { Route as _authenticatedOrgSlugTunnelsTunnelIdRouteImport } from './routes/__authenticated/$orgSlug/tunnels/$tunnelId'
import { Route as _authenticatedOrgSlugSettingsProfileRouteImport } from './routes/__authenticated/$orgSlug/settings/profile'
import { Route as _authenticatedOrgSlugSettingsOrganizationRouteImport } from './routes/__authenticated/$orgSlug/settings/organization'
import { Route as ApiOrgSlugTunnelsTunnelIdStopRouteImport } from './routes/api/$orgSlug/tunnels/$tunnelId.stop'
import { Route as ApiOrgSlugDomainsDomainIdVerifyRouteImport } from './routes/api/$orgSlug/domains/$domainId.verify'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalDomainCheckRoute = InternalDomainCheckRouteImport.update({
  id: '/internal/domain-check',
  path: '/internal/domain-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedOnboardingRoute =
  _authenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedOrgSlugRoute = _authenticatedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedOrgSlugIndexRoute =
  _authenticatedOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelRegisterRoute = ApiTunnelRegisterRouteImport.update({
  id: '/api/tunnel/register',
  path: '/api/tunnel/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelCheckSubdomainRoute = ApiTunnelCheckSubdomainRouteImport.update({
  id: '/api/tunnel/check-subdomain',
  path: '/api/tunnel/check-subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelAuthRoute = ApiTunnelAuthRouteImport.update({
  id: '/api/tunnel/auth',
  path: '/api/tunnel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsOrganizationIdRoute =
  ApiSubscriptionsOrganizationIdRouteImport.update({
    id: '/api/subscriptions/$organizationId',
    path: '/api/subscriptions/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsCheckSlugRoute =
  ApiOrganizationsCheckSlugRouteImport.update({
    id: '/api/organizations/check-slug',
    path: '/api/organizations/check-slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeOrgsRoute = ApiMeOrgsRouteImport.update({
  id: '/api/me/orgs',
  path: '/api/me/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainVerifyOwnershipRoute =
  ApiDomainVerifyOwnershipRouteImport.update({
    id: '/api/domain/verify-ownership',
    path: '/api/domain/verify-ownership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliLoginRoute = ApiCliLoginRouteImport.update({
  id: '/api/cli/login',
  path: '/api/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliExchangeRoute = ApiCliExchangeRouteImport.update({
  id: '/api/cli/exchange',
  path: '/api/cli/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCompleteRoute = ApiCliCompleteRouteImport.update({
  id: '/api/cli/complete',
  path: '/api/cli/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutPolarRoute = ApiCheckoutPolarRouteImport.update({
  id: '/api/checkout/polar',
  path: '/api/checkout/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSubscriptionsRoute = ApiOrgSlugSubscriptionsRouteImport.update({
  id: '/api/$orgSlug/subscriptions',
  path: '/api/$orgSlug/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugRequestsRoute = ApiOrgSlugRequestsRouteImport.update({
  id: '/api/$orgSlug/requests',
  path: '/api/$orgSlug/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugAuthTokensRoute = ApiOrgSlugAuthTokensRouteImport.update({
  id: '/api/$orgSlug/auth-tokens',
  path: '/api/$orgSlug/auth-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedOrgSlugTokensRoute =
  _authenticatedOrgSlugTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugSubdomainsRoute =
  _authenticatedOrgSlugSubdomainsRouteImport.update({
    id: '/subdomains',
    path: '/subdomains',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugSettingsRoute =
  _authenticatedOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugRequestsRoute =
  _authenticatedOrgSlugRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugMembersRoute =
  _authenticatedOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugInstallRoute =
  _authenticatedOrgSlugInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugDomainsRoute =
  _authenticatedOrgSlugDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugBillingRoute =
  _authenticatedOrgSlugBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const ApiOrgSlugTunnelsIndexRoute = ApiOrgSlugTunnelsIndexRouteImport.update({
  id: '/api/$orgSlug/tunnels/',
  path: '/api/$orgSlug/tunnels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSubdomainsIndexRoute =
  ApiOrgSlugSubdomainsIndexRouteImport.update({
    id: '/api/$orgSlug/subdomains/',
    path: '/api/$orgSlug/subdomains/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugDomainsIndexRoute = ApiOrgSlugDomainsIndexRouteImport.update({
  id: '/api/$orgSlug/domains/',
  path: '/api/$orgSlug/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedOrgSlugTunnelsIndexRoute =
  _authenticatedOrgSlugTunnelsIndexRouteImport.update({
    id: '/tunnels/',
    path: '/tunnels/',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugSettingsIndexRoute =
  _authenticatedOrgSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authenticatedOrgSlugSettingsRoute,
  } as any)
const ApiCliLoginStatusRoute = ApiCliLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliLoginRoute,
} as any)
const ApiOrgSlugTunnelsTunnelIdRoute =
  ApiOrgSlugTunnelsTunnelIdRouteImport.update({
    id: '/api/$orgSlug/tunnels/$tunnelId',
    path: '/api/$orgSlug/tunnels/$tunnelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugSubdomainsSubdomainIdRoute =
  ApiOrgSlugSubdomainsSubdomainIdRouteImport.update({
    id: '/api/$orgSlug/subdomains/$subdomainId',
    path: '/api/$orgSlug/subdomains/$subdomainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugStatsTunnelRoute = ApiOrgSlugStatsTunnelRouteImport.update({
  id: '/api/$orgSlug/stats/tunnel',
  path: '/api/$orgSlug/stats/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsProtocolRoute = ApiOrgSlugStatsProtocolRouteImport.update({
  id: '/api/$orgSlug/stats/protocol',
  path: '/api/$orgSlug/stats/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsOverviewRoute = ApiOrgSlugStatsOverviewRouteImport.update({
  id: '/api/$orgSlug/stats/overview',
  path: '/api/$orgSlug/stats/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsBandwidthRoute =
  ApiOrgSlugStatsBandwidthRouteImport.update({
    id: '/api/$orgSlug/stats/bandwidth',
    path: '/api/$orgSlug/stats/bandwidth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugPortalPolarRoute = ApiOrgSlugPortalPolarRouteImport.update({
  id: '/api/$orgSlug/portal/polar',
  path: '/api/$orgSlug/portal/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugDomainsDomainIdRoute =
  ApiOrgSlugDomainsDomainIdRouteImport.update({
    id: '/api/$orgSlug/domains/$domainId',
    path: '/api/$orgSlug/domains/$domainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const _authenticatedOrgSlugTunnelsTunnelIdRoute =
  _authenticatedOrgSlugTunnelsTunnelIdRouteImport.update({
    id: '/tunnels/$tunnelId',
    path: '/tunnels/$tunnelId',
    getParentRoute: () => _authenticatedOrgSlugRoute,
  } as any)
const _authenticatedOrgSlugSettingsProfileRoute =
  _authenticatedOrgSlugSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => _authenticatedOrgSlugSettingsRoute,
  } as any)
const _authenticatedOrgSlugSettingsOrganizationRoute =
  _authenticatedOrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => _authenticatedOrgSlugSettingsRoute,
  } as any)
const ApiOrgSlugTunnelsTunnelIdStopRoute =
  ApiOrgSlugTunnelsTunnelIdStopRouteImport.update({
    id: '/stop',
    path: '/stop',
    getParentRoute: () => ApiOrgSlugTunnelsTunnelIdRoute,
  } as any)
const ApiOrgSlugDomainsDomainIdVerifyRoute =
  ApiOrgSlugDomainsDomainIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiOrgSlugDomainsDomainIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug': typeof _authenticatedOrgSlugRouteWithChildren
  '/onboarding': typeof _authenticatedOnboardingRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/billing': typeof _authenticatedOrgSlugBillingRoute
  '/$orgSlug/domains': typeof _authenticatedOrgSlugDomainsRoute
  '/$orgSlug/install': typeof _authenticatedOrgSlugInstallRoute
  '/$orgSlug/members': typeof _authenticatedOrgSlugMembersRoute
  '/$orgSlug/requests': typeof _authenticatedOrgSlugRequestsRoute
  '/$orgSlug/settings': typeof _authenticatedOrgSlugSettingsRouteWithChildren
  '/$orgSlug/subdomains': typeof _authenticatedOrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof _authenticatedOrgSlugTokensRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/': typeof _authenticatedOrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof _authenticatedOrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof _authenticatedOrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof _authenticatedOrgSlugTunnelsTunnelIdRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/$orgSlug/settings/': typeof _authenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof _authenticatedOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof _authenticatedOnboardingRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/billing': typeof _authenticatedOrgSlugBillingRoute
  '/$orgSlug/domains': typeof _authenticatedOrgSlugDomainsRoute
  '/$orgSlug/install': typeof _authenticatedOrgSlugInstallRoute
  '/$orgSlug/members': typeof _authenticatedOrgSlugMembersRoute
  '/$orgSlug/requests': typeof _authenticatedOrgSlugRequestsRoute
  '/$orgSlug/subdomains': typeof _authenticatedOrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof _authenticatedOrgSlugTokensRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug': typeof _authenticatedOrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof _authenticatedOrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof _authenticatedOrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof _authenticatedOrgSlugTunnelsTunnelIdRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/$orgSlug/settings': typeof _authenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof _authenticatedOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/__authenticated/$orgSlug': typeof _authenticatedOrgSlugRouteWithChildren
  '/__authenticated/onboarding': typeof _authenticatedOnboardingRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/__authenticated/$orgSlug/billing': typeof _authenticatedOrgSlugBillingRoute
  '/__authenticated/$orgSlug/domains': typeof _authenticatedOrgSlugDomainsRoute
  '/__authenticated/$orgSlug/install': typeof _authenticatedOrgSlugInstallRoute
  '/__authenticated/$orgSlug/members': typeof _authenticatedOrgSlugMembersRoute
  '/__authenticated/$orgSlug/requests': typeof _authenticatedOrgSlugRequestsRoute
  '/__authenticated/$orgSlug/settings': typeof _authenticatedOrgSlugSettingsRouteWithChildren
  '/__authenticated/$orgSlug/subdomains': typeof _authenticatedOrgSlugSubdomainsRoute
  '/__authenticated/$orgSlug/tokens': typeof _authenticatedOrgSlugTokensRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/__authenticated/$orgSlug/': typeof _authenticatedOrgSlugIndexRoute
  '/__authenticated/$orgSlug/settings/organization': typeof _authenticatedOrgSlugSettingsOrganizationRoute
  '/__authenticated/$orgSlug/settings/profile': typeof _authenticatedOrgSlugSettingsProfileRoute
  '/__authenticated/$orgSlug/tunnels/$tunnelId': typeof _authenticatedOrgSlugTunnelsTunnelIdRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/__authenticated/$orgSlug/settings/': typeof _authenticatedOrgSlugSettingsIndexRoute
  '/__authenticated/$orgSlug/tunnels/': typeof _authenticatedOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains/': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels/': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/$orgSlug'
    | '/onboarding'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/polar'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/cli/login/status'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels'
    | '/api/$orgSlug/domains'
    | '/api/$orgSlug/subdomains'
    | '/api/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/onboarding'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/polar'
    | '/$orgSlug'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/cli/login/status'
    | '/$orgSlug/settings'
    | '/$orgSlug/tunnels'
    | '/api/$orgSlug/domains'
    | '/api/$orgSlug/subdomains'
    | '/api/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/__authenticated/$orgSlug'
    | '/__authenticated/onboarding'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/__authenticated/$orgSlug/billing'
    | '/__authenticated/$orgSlug/domains'
    | '/__authenticated/$orgSlug/install'
    | '/__authenticated/$orgSlug/members'
    | '/__authenticated/$orgSlug/requests'
    | '/__authenticated/$orgSlug/settings'
    | '/__authenticated/$orgSlug/subdomains'
    | '/__authenticated/$orgSlug/tokens'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/polar'
    | '/__authenticated/$orgSlug/'
    | '/__authenticated/$orgSlug/settings/organization'
    | '/__authenticated/$orgSlug/settings/profile'
    | '/__authenticated/$orgSlug/tunnels/$tunnelId'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/cli/login/status'
    | '/__authenticated/$orgSlug/settings/'
    | '/__authenticated/$orgSlug/tunnels/'
    | '/api/$orgSlug/domains/'
    | '/api/$orgSlug/subdomains/'
    | '/api/$orgSlug/tunnels/'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SelectRoute: typeof SelectRoute
  SignupRoute: typeof SignupRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CliLoginRoute: typeof CliLoginRoute
  DocsSplatRoute: typeof DocsSplatRoute
  InternalDomainCheckRoute: typeof InternalDomainCheckRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  ApiOrgSlugAuthTokensRoute: typeof ApiOrgSlugAuthTokensRoute
  ApiOrgSlugRequestsRoute: typeof ApiOrgSlugRequestsRoute
  ApiOrgSlugSubscriptionsRoute: typeof ApiOrgSlugSubscriptionsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutPolarRoute: typeof ApiCheckoutPolarRoute
  ApiCliCompleteRoute: typeof ApiCliCompleteRoute
  ApiCliExchangeRoute: typeof ApiCliExchangeRoute
  ApiCliLoginRoute: typeof ApiCliLoginRouteWithChildren
  ApiDomainVerifyOwnershipRoute: typeof ApiDomainVerifyOwnershipRoute
  ApiMeOrgsRoute: typeof ApiMeOrgsRoute
  ApiOrganizationsCheckSlugRoute: typeof ApiOrganizationsCheckSlugRoute
  ApiSubscriptionsOrganizationIdRoute: typeof ApiSubscriptionsOrganizationIdRoute
  ApiTunnelAuthRoute: typeof ApiTunnelAuthRoute
  ApiTunnelCheckSubdomainRoute: typeof ApiTunnelCheckSubdomainRoute
  ApiTunnelRegisterRoute: typeof ApiTunnelRegisterRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
  ApiOrgSlugDomainsDomainIdRoute: typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  ApiOrgSlugPortalPolarRoute: typeof ApiOrgSlugPortalPolarRoute
  ApiOrgSlugStatsBandwidthRoute: typeof ApiOrgSlugStatsBandwidthRoute
  ApiOrgSlugStatsOverviewRoute: typeof ApiOrgSlugStatsOverviewRoute
  ApiOrgSlugStatsProtocolRoute: typeof ApiOrgSlugStatsProtocolRoute
  ApiOrgSlugStatsTunnelRoute: typeof ApiOrgSlugStatsTunnelRoute
  ApiOrgSlugSubdomainsSubdomainIdRoute: typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  ApiOrgSlugTunnelsTunnelIdRoute: typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  ApiOrgSlugDomainsIndexRoute: typeof ApiOrgSlugDomainsIndexRoute
  ApiOrgSlugSubdomainsIndexRoute: typeof ApiOrgSlugSubdomainsIndexRoute
  ApiOrgSlugTunnelsIndexRoute: typeof ApiOrgSlugTunnelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/domain-check': {
      id: '/internal/domain-check'
      path: '/internal/domain-check'
      fullPath: '/internal/domain-check'
      preLoaderRoute: typeof InternalDomainCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/login': {
      id: '/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/onboarding': {
      id: '/__authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof _authenticatedOnboardingRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/$orgSlug': {
      id: '/__authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof _authenticatedOrgSlugRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/$orgSlug/': {
      id: '/__authenticated/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof _authenticatedOrgSlugIndexRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/register': {
      id: '/api/tunnel/register'
      path: '/api/tunnel/register'
      fullPath: '/api/tunnel/register'
      preLoaderRoute: typeof ApiTunnelRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/check-subdomain': {
      id: '/api/tunnel/check-subdomain'
      path: '/api/tunnel/check-subdomain'
      fullPath: '/api/tunnel/check-subdomain'
      preLoaderRoute: typeof ApiTunnelCheckSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/auth': {
      id: '/api/tunnel/auth'
      path: '/api/tunnel/auth'
      fullPath: '/api/tunnel/auth'
      preLoaderRoute: typeof ApiTunnelAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/$organizationId': {
      id: '/api/subscriptions/$organizationId'
      path: '/api/subscriptions/$organizationId'
      fullPath: '/api/subscriptions/$organizationId'
      preLoaderRoute: typeof ApiSubscriptionsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/check-slug': {
      id: '/api/organizations/check-slug'
      path: '/api/organizations/check-slug'
      fullPath: '/api/organizations/check-slug'
      preLoaderRoute: typeof ApiOrganizationsCheckSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/orgs': {
      id: '/api/me/orgs'
      path: '/api/me/orgs'
      fullPath: '/api/me/orgs'
      preLoaderRoute: typeof ApiMeOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain/verify-ownership': {
      id: '/api/domain/verify-ownership'
      path: '/api/domain/verify-ownership'
      fullPath: '/api/domain/verify-ownership'
      preLoaderRoute: typeof ApiDomainVerifyOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login': {
      id: '/api/cli/login'
      path: '/api/cli/login'
      fullPath: '/api/cli/login'
      preLoaderRoute: typeof ApiCliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/exchange': {
      id: '/api/cli/exchange'
      path: '/api/cli/exchange'
      fullPath: '/api/cli/exchange'
      preLoaderRoute: typeof ApiCliExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/complete': {
      id: '/api/cli/complete'
      path: '/api/cli/complete'
      fullPath: '/api/cli/complete'
      preLoaderRoute: typeof ApiCliCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/polar': {
      id: '/api/checkout/polar'
      path: '/api/checkout/polar'
      fullPath: '/api/checkout/polar'
      preLoaderRoute: typeof ApiCheckoutPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subscriptions': {
      id: '/api/$orgSlug/subscriptions'
      path: '/api/$orgSlug/subscriptions'
      fullPath: '/api/$orgSlug/subscriptions'
      preLoaderRoute: typeof ApiOrgSlugSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/requests': {
      id: '/api/$orgSlug/requests'
      path: '/api/$orgSlug/requests'
      fullPath: '/api/$orgSlug/requests'
      preLoaderRoute: typeof ApiOrgSlugRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/auth-tokens': {
      id: '/api/$orgSlug/auth-tokens'
      path: '/api/$orgSlug/auth-tokens'
      fullPath: '/api/$orgSlug/auth-tokens'
      preLoaderRoute: typeof ApiOrgSlugAuthTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/$orgSlug/tokens': {
      id: '/__authenticated/$orgSlug/tokens'
      path: '/tokens'
      fullPath: '/$orgSlug/tokens'
      preLoaderRoute: typeof _authenticatedOrgSlugTokensRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/subdomains': {
      id: '/__authenticated/$orgSlug/subdomains'
      path: '/subdomains'
      fullPath: '/$orgSlug/subdomains'
      preLoaderRoute: typeof _authenticatedOrgSlugSubdomainsRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/settings': {
      id: '/__authenticated/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof _authenticatedOrgSlugSettingsRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/requests': {
      id: '/__authenticated/$orgSlug/requests'
      path: '/requests'
      fullPath: '/$orgSlug/requests'
      preLoaderRoute: typeof _authenticatedOrgSlugRequestsRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/members': {
      id: '/__authenticated/$orgSlug/members'
      path: '/members'
      fullPath: '/$orgSlug/members'
      preLoaderRoute: typeof _authenticatedOrgSlugMembersRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/install': {
      id: '/__authenticated/$orgSlug/install'
      path: '/install'
      fullPath: '/$orgSlug/install'
      preLoaderRoute: typeof _authenticatedOrgSlugInstallRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/domains': {
      id: '/__authenticated/$orgSlug/domains'
      path: '/domains'
      fullPath: '/$orgSlug/domains'
      preLoaderRoute: typeof _authenticatedOrgSlugDomainsRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/billing': {
      id: '/__authenticated/$orgSlug/billing'
      path: '/billing'
      fullPath: '/$orgSlug/billing'
      preLoaderRoute: typeof _authenticatedOrgSlugBillingRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/api/$orgSlug/tunnels/': {
      id: '/api/$orgSlug/tunnels/'
      path: '/api/$orgSlug/tunnels'
      fullPath: '/api/$orgSlug/tunnels'
      preLoaderRoute: typeof ApiOrgSlugTunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subdomains/': {
      id: '/api/$orgSlug/subdomains/'
      path: '/api/$orgSlug/subdomains'
      fullPath: '/api/$orgSlug/subdomains'
      preLoaderRoute: typeof ApiOrgSlugSubdomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/domains/': {
      id: '/api/$orgSlug/domains/'
      path: '/api/$orgSlug/domains'
      fullPath: '/api/$orgSlug/domains'
      preLoaderRoute: typeof ApiOrgSlugDomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/$orgSlug/tunnels/': {
      id: '/__authenticated/$orgSlug/tunnels/'
      path: '/tunnels'
      fullPath: '/$orgSlug/tunnels'
      preLoaderRoute: typeof _authenticatedOrgSlugTunnelsIndexRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/settings/': {
      id: '/__authenticated/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof _authenticatedOrgSlugSettingsIndexRouteImport
      parentRoute: typeof _authenticatedOrgSlugSettingsRoute
    }
    '/api/cli/login/status': {
      id: '/api/cli/login/status'
      path: '/status'
      fullPath: '/api/cli/login/status'
      preLoaderRoute: typeof ApiCliLoginStatusRouteImport
      parentRoute: typeof ApiCliLoginRoute
    }
    '/api/$orgSlug/tunnels/$tunnelId': {
      id: '/api/$orgSlug/tunnels/$tunnelId'
      path: '/api/$orgSlug/tunnels/$tunnelId'
      fullPath: '/api/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof ApiOrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subdomains/$subdomainId': {
      id: '/api/$orgSlug/subdomains/$subdomainId'
      path: '/api/$orgSlug/subdomains/$subdomainId'
      fullPath: '/api/$orgSlug/subdomains/$subdomainId'
      preLoaderRoute: typeof ApiOrgSlugSubdomainsSubdomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/tunnel': {
      id: '/api/$orgSlug/stats/tunnel'
      path: '/api/$orgSlug/stats/tunnel'
      fullPath: '/api/$orgSlug/stats/tunnel'
      preLoaderRoute: typeof ApiOrgSlugStatsTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/protocol': {
      id: '/api/$orgSlug/stats/protocol'
      path: '/api/$orgSlug/stats/protocol'
      fullPath: '/api/$orgSlug/stats/protocol'
      preLoaderRoute: typeof ApiOrgSlugStatsProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/overview': {
      id: '/api/$orgSlug/stats/overview'
      path: '/api/$orgSlug/stats/overview'
      fullPath: '/api/$orgSlug/stats/overview'
      preLoaderRoute: typeof ApiOrgSlugStatsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/bandwidth': {
      id: '/api/$orgSlug/stats/bandwidth'
      path: '/api/$orgSlug/stats/bandwidth'
      fullPath: '/api/$orgSlug/stats/bandwidth'
      preLoaderRoute: typeof ApiOrgSlugStatsBandwidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/portal/polar': {
      id: '/api/$orgSlug/portal/polar'
      path: '/api/$orgSlug/portal/polar'
      fullPath: '/api/$orgSlug/portal/polar'
      preLoaderRoute: typeof ApiOrgSlugPortalPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/domains/$domainId': {
      id: '/api/$orgSlug/domains/$domainId'
      path: '/api/$orgSlug/domains/$domainId'
      fullPath: '/api/$orgSlug/domains/$domainId'
      preLoaderRoute: typeof ApiOrgSlugDomainsDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/$orgSlug/tunnels/$tunnelId': {
      id: '/__authenticated/$orgSlug/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof _authenticatedOrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof _authenticatedOrgSlugRoute
    }
    '/__authenticated/$orgSlug/settings/profile': {
      id: '/__authenticated/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof _authenticatedOrgSlugSettingsProfileRouteImport
      parentRoute: typeof _authenticatedOrgSlugSettingsRoute
    }
    '/__authenticated/$orgSlug/settings/organization': {
      id: '/__authenticated/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof _authenticatedOrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof _authenticatedOrgSlugSettingsRoute
    }
    '/api/$orgSlug/tunnels/$tunnelId/stop': {
      id: '/api/$orgSlug/tunnels/$tunnelId/stop'
      path: '/stop'
      fullPath: '/api/$orgSlug/tunnels/$tunnelId/stop'
      preLoaderRoute: typeof ApiOrgSlugTunnelsTunnelIdStopRouteImport
      parentRoute: typeof ApiOrgSlugTunnelsTunnelIdRoute
    }
    '/api/$orgSlug/domains/$domainId/verify': {
      id: '/api/$orgSlug/domains/$domainId/verify'
      path: '/verify'
      fullPath: '/api/$orgSlug/domains/$domainId/verify'
      preLoaderRoute: typeof ApiOrgSlugDomainsDomainIdVerifyRouteImport
      parentRoute: typeof ApiOrgSlugDomainsDomainIdRoute
    }
  }
}

interface _authenticatedOrgSlugSettingsRouteChildren {
  _authenticatedOrgSlugSettingsOrganizationRoute: typeof _authenticatedOrgSlugSettingsOrganizationRoute
  _authenticatedOrgSlugSettingsProfileRoute: typeof _authenticatedOrgSlugSettingsProfileRoute
  _authenticatedOrgSlugSettingsIndexRoute: typeof _authenticatedOrgSlugSettingsIndexRoute
}

const _authenticatedOrgSlugSettingsRouteChildren: _authenticatedOrgSlugSettingsRouteChildren =
  {
    _authenticatedOrgSlugSettingsOrganizationRoute:
      _authenticatedOrgSlugSettingsOrganizationRoute,
    _authenticatedOrgSlugSettingsProfileRoute:
      _authenticatedOrgSlugSettingsProfileRoute,
    _authenticatedOrgSlugSettingsIndexRoute:
      _authenticatedOrgSlugSettingsIndexRoute,
  }

const _authenticatedOrgSlugSettingsRouteWithChildren =
  _authenticatedOrgSlugSettingsRoute._addFileChildren(
    _authenticatedOrgSlugSettingsRouteChildren,
  )

interface _authenticatedOrgSlugRouteChildren {
  _authenticatedOrgSlugBillingRoute: typeof _authenticatedOrgSlugBillingRoute
  _authenticatedOrgSlugDomainsRoute: typeof _authenticatedOrgSlugDomainsRoute
  _authenticatedOrgSlugInstallRoute: typeof _authenticatedOrgSlugInstallRoute
  _authenticatedOrgSlugMembersRoute: typeof _authenticatedOrgSlugMembersRoute
  _authenticatedOrgSlugRequestsRoute: typeof _authenticatedOrgSlugRequestsRoute
  _authenticatedOrgSlugSettingsRoute: typeof _authenticatedOrgSlugSettingsRouteWithChildren
  _authenticatedOrgSlugSubdomainsRoute: typeof _authenticatedOrgSlugSubdomainsRoute
  _authenticatedOrgSlugTokensRoute: typeof _authenticatedOrgSlugTokensRoute
  _authenticatedOrgSlugIndexRoute: typeof _authenticatedOrgSlugIndexRoute
  _authenticatedOrgSlugTunnelsTunnelIdRoute: typeof _authenticatedOrgSlugTunnelsTunnelIdRoute
  _authenticatedOrgSlugTunnelsIndexRoute: typeof _authenticatedOrgSlugTunnelsIndexRoute
}

const _authenticatedOrgSlugRouteChildren: _authenticatedOrgSlugRouteChildren = {
  _authenticatedOrgSlugBillingRoute: _authenticatedOrgSlugBillingRoute,
  _authenticatedOrgSlugDomainsRoute: _authenticatedOrgSlugDomainsRoute,
  _authenticatedOrgSlugInstallRoute: _authenticatedOrgSlugInstallRoute,
  _authenticatedOrgSlugMembersRoute: _authenticatedOrgSlugMembersRoute,
  _authenticatedOrgSlugRequestsRoute: _authenticatedOrgSlugRequestsRoute,
  _authenticatedOrgSlugSettingsRoute:
    _authenticatedOrgSlugSettingsRouteWithChildren,
  _authenticatedOrgSlugSubdomainsRoute: _authenticatedOrgSlugSubdomainsRoute,
  _authenticatedOrgSlugTokensRoute: _authenticatedOrgSlugTokensRoute,
  _authenticatedOrgSlugIndexRoute: _authenticatedOrgSlugIndexRoute,
  _authenticatedOrgSlugTunnelsTunnelIdRoute:
    _authenticatedOrgSlugTunnelsTunnelIdRoute,
  _authenticatedOrgSlugTunnelsIndexRoute:
    _authenticatedOrgSlugTunnelsIndexRoute,
}

const _authenticatedOrgSlugRouteWithChildren =
  _authenticatedOrgSlugRoute._addFileChildren(
    _authenticatedOrgSlugRouteChildren,
  )

interface _authenticatedRouteChildren {
  _authenticatedOrgSlugRoute: typeof _authenticatedOrgSlugRouteWithChildren
  _authenticatedOnboardingRoute: typeof _authenticatedOnboardingRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedOrgSlugRoute: _authenticatedOrgSlugRouteWithChildren,
  _authenticatedOnboardingRoute: _authenticatedOnboardingRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

interface ApiCliLoginRouteChildren {
  ApiCliLoginStatusRoute: typeof ApiCliLoginStatusRoute
}

const ApiCliLoginRouteChildren: ApiCliLoginRouteChildren = {
  ApiCliLoginStatusRoute: ApiCliLoginStatusRoute,
}

const ApiCliLoginRouteWithChildren = ApiCliLoginRoute._addFileChildren(
  ApiCliLoginRouteChildren,
)

interface ApiOrgSlugDomainsDomainIdRouteChildren {
  ApiOrgSlugDomainsDomainIdVerifyRoute: typeof ApiOrgSlugDomainsDomainIdVerifyRoute
}

const ApiOrgSlugDomainsDomainIdRouteChildren: ApiOrgSlugDomainsDomainIdRouteChildren =
  {
    ApiOrgSlugDomainsDomainIdVerifyRoute: ApiOrgSlugDomainsDomainIdVerifyRoute,
  }

const ApiOrgSlugDomainsDomainIdRouteWithChildren =
  ApiOrgSlugDomainsDomainIdRoute._addFileChildren(
    ApiOrgSlugDomainsDomainIdRouteChildren,
  )

interface ApiOrgSlugTunnelsTunnelIdRouteChildren {
  ApiOrgSlugTunnelsTunnelIdStopRoute: typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}

const ApiOrgSlugTunnelsTunnelIdRouteChildren: ApiOrgSlugTunnelsTunnelIdRouteChildren =
  {
    ApiOrgSlugTunnelsTunnelIdStopRoute: ApiOrgSlugTunnelsTunnelIdStopRoute,
  }

const ApiOrgSlugTunnelsTunnelIdRouteWithChildren =
  ApiOrgSlugTunnelsTunnelIdRoute._addFileChildren(
    ApiOrgSlugTunnelsTunnelIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authenticatedRoute: _authenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  EmailTemplatesRoute: EmailTemplatesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SelectRoute: SelectRoute,
  SignupRoute: SignupRoute,
  ApiSearchRoute: ApiSearchRoute,
  CliLoginRoute: CliLoginRoute,
  DocsSplatRoute: DocsSplatRoute,
  InternalDomainCheckRoute: InternalDomainCheckRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  ApiOrgSlugAuthTokensRoute: ApiOrgSlugAuthTokensRoute,
  ApiOrgSlugRequestsRoute: ApiOrgSlugRequestsRoute,
  ApiOrgSlugSubscriptionsRoute: ApiOrgSlugSubscriptionsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutPolarRoute: ApiCheckoutPolarRoute,
  ApiCliCompleteRoute: ApiCliCompleteRoute,
  ApiCliExchangeRoute: ApiCliExchangeRoute,
  ApiCliLoginRoute: ApiCliLoginRouteWithChildren,
  ApiDomainVerifyOwnershipRoute: ApiDomainVerifyOwnershipRoute,
  ApiMeOrgsRoute: ApiMeOrgsRoute,
  ApiOrganizationsCheckSlugRoute: ApiOrganizationsCheckSlugRoute,
  ApiSubscriptionsOrganizationIdRoute: ApiSubscriptionsOrganizationIdRoute,
  ApiTunnelAuthRoute: ApiTunnelAuthRoute,
  ApiTunnelCheckSubdomainRoute: ApiTunnelCheckSubdomainRoute,
  ApiTunnelRegisterRoute: ApiTunnelRegisterRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
  ApiOrgSlugDomainsDomainIdRoute: ApiOrgSlugDomainsDomainIdRouteWithChildren,
  ApiOrgSlugPortalPolarRoute: ApiOrgSlugPortalPolarRoute,
  ApiOrgSlugStatsBandwidthRoute: ApiOrgSlugStatsBandwidthRoute,
  ApiOrgSlugStatsOverviewRoute: ApiOrgSlugStatsOverviewRoute,
  ApiOrgSlugStatsProtocolRoute: ApiOrgSlugStatsProtocolRoute,
  ApiOrgSlugStatsTunnelRoute: ApiOrgSlugStatsTunnelRoute,
  ApiOrgSlugSubdomainsSubdomainIdRoute: ApiOrgSlugSubdomainsSubdomainIdRoute,
  ApiOrgSlugTunnelsTunnelIdRoute: ApiOrgSlugTunnelsTunnelIdRouteWithChildren,
  ApiOrgSlugDomainsIndexRoute: ApiOrgSlugDomainsIndexRoute,
  ApiOrgSlugSubdomainsIndexRoute: ApiOrgSlugSubdomainsIndexRoute,
  ApiOrgSlugTunnelsIndexRoute: ApiOrgSlugTunnelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
